### ISSUE TITLE
Vanilla install requires geojson and geopandas

### ISSUE THREAD

**Issue by dtasgaon** [mattijn/topojson#4]
The readme suggests that the `geojson` and `geopandas` dependencies are only for testing.

However, when I install using `pip install topojson`, and then import and use the library, I run into dependency issues. Did I misunderstand the dependencies?

```
Traceback (most recent call last):
  File "geography.py", line 9, in <module>
    import topojson
  File "/Users/deven/projects/instant/venv/lib/python3.6/site-packages/topojson/__init__.py", line 4, in <module>
    from .extract import extract
  File "/Users/deven/projects/instant/venv/lib/python3.6/site-packages/topojson/extract.py", line 17, in <module>
    class Extract:
  File "/Users/deven/projects/instant/venv/lib/python3.6/site-packages/topojson/extract.py", line 190, in Extract
    @serialize_geom_type.register(geojson.FeatureCollection)
NameError: name 'geojson' is not defined
```

I installed `geojson` once I saw the above error. Then I received the following error:

```
Traceback (most recent call last):
  File "geography.py", line 9, in <module>
    import topojson
  File "/Users/deven/projects/instant/venv/lib/python3.6/site-packages/topojson/__init__.py", line 4, in <module>
    from .extract import extract
  File "/Users/deven/projects/instant/venv/lib/python3.6/site-packages/topojson/extract.py", line 17, in <module>
    class Extract:
  File "/Users/deven/projects/instant/venv/lib/python3.6/site-packages/topojson/extract.py", line 233, in Extract
    @serialize_geom_type.register(geopandas.GeoDataFrame)
NameError: name 'geopandas' is not defined
```

Given that `geopandas` has quite a few dependencies, I figured I'll check first if I'm doing this right.

Would greatly appreciate any guidance. Thanks!!

**Comment by mattijn** [comment]
Thanks for raising the issue!

You are right. I tried to avoid the need of installing of both `geojson` and `geopandas`, since especially `geopandas` has a lot of dependencies that are not easy to install on windows. 

In https://github.com/mattijn/topojson/pull/5 I have addressed this issue and with the next release this dependency issue should be solved.
